# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    run_tests(workspace: "Pelina Beer App.xcworkspace", devices: ["iPhone 8"], scheme: "Pelina Beer App")
    build_app(workspace: "Pelina Beer App.xcworkspace", scheme: "Pelina Beer App", clean: true, silent: true, include_bitcode: false, export_xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
  end
end
